imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sylius.yml }

framework:
    translator:      { fallback: %sylius.locale% }
    secret:          %sylius.secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  "%sylius.locale%"
    trusted_proxies: ~
    session:
        cookie_domain: .%misi.base_host%

twig:
    form:
        resources:
            - 'SyliusWebBundle::forms.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['SyliusWebBundle']
    filters:
        cssrewrite: ~

doctrine:
    dbal:
      connections:
        default:
            driver:   %sylius.database.driver%
            host:     %sylius.database.host%
            port:     %sylius.database.port%
            dbname:   %sylius.database.name%
            user:     %sylius.database.user%
            password: %sylius.database.password%
            charset:  UTF8
        legacy:
            driver:   %misi.database_legacy.driver%
            host:     %misi.database_legacy.host%
            port:     %misi.database_legacy.port%
            dbname:   %misi.database_legacy.name%
            user:     %misi.database_legacy.user%
            password: %misi.database_legacy.password%
            charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

stof_doctrine_extensions:
    default_locale: %sylius.locale%
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Sylius\Bundle\CoreBundle\Model\User
    profile:
        form:
            type: sylius_user_profile
    registration:
        form:
            type: sylius_user_registration

fos_message:
    db_driver: orm
    thread_class: Misi\Bundle\MessageBundle\Model\Thread
    message_class: Misi\Bundle\MessageBundle\Model\Message
  
swiftmailer:
    transport: %sylius.mailer.transport%
    host:      %sylius.mailer.host%
    username:  %sylius.mailer.user%
    password:  %sylius.mailer.password%
    spool:     { type: memory }

liip_doctrine_cache:
    namespaces:
        sylius_settings:
            type: %sylius.cache%

knp_gaufrette:
    adapters:
        sylius_image:
            local:
                directory:  %kernel.root_dir%/../web/media/image
                create:     true
    filesystems:
        sylius_image:
            adapter: sylius_image

liip_imagine:
    data_root: %kernel.root_dir%/../web/media/image
    filter_sets:
        sylius_16x16:
            filters:
                thumbnail: { size: [16, 16], mode: outbound }
        sylius_50x40:
            filters:
                thumbnail: { size: [50, 40], mode: outbound }
        sylius_90x60:
            filters:
                thumbnail: { size: [90, 60], mode: outbound }
        sylius_200x200:
            filters:
                thumbnail: { size: [200, 200], mode: outbound }

        sylius_262x255:
            filters:
                thumbnail: { size: [265, 255], mode: outbound }
        sylius_310x300:
            filters:
                thumbnail: { size: [310, 300], mode: outbound }
        sylius_610x600:
            filters:
                thumbnail: { size: [610, 600], mode: outbound }
        sylius_gallery:
            filters:
                thumbnail: { size: [640, 480], mode: outbound }

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/bin/wkhtmltoimage
        options:    []
        
hwi_oauth:
    connect: true
    firewall_name: main
    fosub: 
      username_iterations: 30
      properties:
        # these properties will be used/redefined later in the custom FOSUBUserProvider service.
        facebook: facebookId
        twitter: twitterId      
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%misi.oauth.facebook.client_id%"
            client_secret:       "%misi.oauth.facebook.client_secret%"
            scope:               "email"   
            paths:
              email: email
              firstname: first_name
              lastname: last_name
              locale: locale
        twitter:
            type: twitter
            client_id: %misi.oauth.twitter.client_id%
            client_secret: %misi.oauth.twitter.client_secret%


