# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

security:
    providers:
        fos_userbundle:
            id: sylius.repository.user
    encoders:
        FOS\UserBundle\Model\UserInterface: 
            id: misi_user.security.encoder.sha256_salted_encoder
    firewalls:
        main:
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                use_referer: true
            remember_me:
                key: %sylius.secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            # cant work as atm there is a bug in php < 5.4.11 with session invalidation
            # https://github.com/symfony/symfony/issues/5868
            # logout: true
            logout: 
                path: fos_user_security_logout
                target: /
                invalidate_session: false
            anonymous: true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/administration.*", role: ROLE_SYLIUS_ADMIN }
        - { path: "/account.*", role: ROLE_USER }
        - { path: "/_partial.*", ip: 127.0.0.1 }
