sylius_core:
    driver: doctrine/orm

sylius_installer:
    classes:
        user:
            model: Sylius\Bundle\CoreBundle\Model\User

sylius_money:
    driver: doctrine/orm
    currency: %sylius.currency%
    locale: %sylius.locale%

sylius_cart:
    resolver: sylius.cart_item_resolver.default
    classes:
        item:
            form: Sylius\Bundle\CoreBundle\Form\Type\CartItemType

sylius_settings:
    driver: doctrine/orm
    classes:
        parameter:
            model: Galoo\Bundle\ShopBundle\Model\Parameter

sylius_taxonomies:
    driver: doctrine/orm
    classes:
        taxonomy:
            model: Sylius\Bundle\CoreBundle\Model\Taxonomy
            form: Sylius\Bundle\CoreBundle\Form\Type\TaxonomyType
        taxon:
            model: Sylius\Bundle\CoreBundle\Model\Taxon
            form: Sylius\Bundle\CoreBundle\Form\Type\TaxonType

sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Sylius\Bundle\CoreBundle\Model\Product
            controller: Sylius\Bundle\CoreBundle\Controller\ProductController
            repository: Sylius\Bundle\CoreBundle\Repository\ProductRepository
            form: Sylius\Bundle\CoreBundle\Form\Type\ProductType

sylius_variable_product:
    classes:
        variant:
            model: Sylius\Bundle\CoreBundle\Model\Variant
            form: Sylius\Bundle\CoreBundle\Form\Type\VariantType

sylius_taxation:
    driver: doctrine/orm
    classes:
        tax_rate:
            model: Sylius\Bundle\CoreBundle\Model\TaxRate
            form: Sylius\Bundle\CoreBundle\Form\Type\TaxRateType

sylius_shipping:
    driver: doctrine/orm
    classes:
        shipment:
            model: Sylius\Bundle\CoreBundle\Model\Shipment
        shipment_item:
            model: Sylius\Bundle\CoreBundle\Model\InventoryUnit
        shipping_method:
            model: Sylius\Bundle\CoreBundle\Model\ShippingMethod
            form: Sylius\Bundle\CoreBundle\Form\Type\ShippingMethodType

sylius_promotions:
    driver: doctrine/orm

sylius_inventory:
    driver: doctrine/orm
    backorders: true
    classes:
        unit:
            model: Sylius\Bundle\CoreBundle\Model\InventoryUnit
        stockable:
            model: %sylius.model.variant.class%
            
sylius_payments:
    driver: doctrine/orm
    gateways:
        dummy: Test
        stripe: Stripe

sylius_addressing:
    driver: doctrine/orm

sylius_sales:
    driver: doctrine/orm
    classes:
        order:
            model: Sylius\Bundle\CoreBundle\Model\Order
            controller: Sylius\Bundle\CoreBundle\Controller\OrderController
            repository: Sylius\Bundle\CoreBundle\Repository\OrderRepository
            form: Sylius\Bundle\CoreBundle\Form\Type\OrderType
        order_item:
            model: Sylius\Bundle\CoreBundle\Model\OrderItem

sylius_resource:
    resources:
        sylius.user:
            driver: doctrine/orm
            classes:
                model: Sylius\Bundle\CoreBundle\Model\User
                controller: Sylius\Bundle\CoreBundle\Controller\UserController
                repository: Sylius\Bundle\CoreBundle\Repository\UserRepository

galoo_shop:
    driver: doctrine/orm
    classes:
        shop:
            model: Sylius\Bundle\CoreBundle\Model\Shop
            controller: Galoo\Bundle\ShopBundle\Controller\ShopController
            repository: Galoo\Bundle\ShopBundle\Repository\ShopRepository
            form: Galoo\Bundle\ShopBundle\Form\Type\ShopType
        payment_method:
            model: Galoo\Bundle\ShopBundle\Model\PaymentMethod
            repository: Galoo\Bundle\ShopBundle\Repository\ShopRepository
            
misi_user:
    driver: doctrine/orm
    product_fee: 
      enabled: true
      #amount 20 = 20 cents
      amount: 20 
      currency: %sylius.currency%
    classes:
        product_fee:
            model: Misi\Bundle\UserBundle\Model\UserFeeProduct
            repository: Misi\Bundle\UserBundle\Repository\UserFeeProductRepository
  
