# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_order_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexByShopAction
        _sylius:
            template: SyliusWebBundle:Shop/Order:index.html.twig
            method: createFilterPaginator
            arguments: [$criteria, $sorting]

sylius_shop_order_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.order:createAction
        _sylius:
            template: SyliusWebBundle:Shop/Order:create.html.twig
            redirect: sylius_shop_order_show

sylius_shop_order_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            template: SyliusWebBundle:Shop/Order:update.html.twig
            redirect: sylius_shop_order_show

sylius_shop_order_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.order:deleteAction
        _sylius:
            redirect: sylius_shop_order_index

sylius_shop_order_filter_form:
    pattern: /filter-form
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:filterFormAction
        _sylius:
            template: SyliusWebBundle:Shop/Order:filterForm.html.twig

sylius_shop_order_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            template: SyliusWebBundle:Shop/Order:show.html.twig

sylius_shop_order_by_user:
    pattern: /u/{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexByUserAction
        _sylius:
            template: SyliusWebBundle:Shop/Order:indexByUser.html.twig
            sortable: true
            sorting: { updatedAt: desc }
