# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_payment_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.payment:indexAction
        _sylius:
            template: SyliusWebBundle:Shop/Payment:index.html.twig
            sortable: true

sylius_shop_payment_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.payment:createAction
        _sylius:
                template: SyliusWebBundle:Shop/Payment:create.html.twig
                redirect: sylius_shop_payment_index

sylius_shop_payment_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.payment:updateAction
        _sylius:
            template: SyliusWebBundle:Shop/Payment:update.html.twig
            redirect: sylius_shop_payment_index

sylius_shop_payment_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.payment:deleteAction
        _sylius:
            redirect: sylius_shop_payment_index

sylius_shop_payment_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.payment:deleteAction
        _sylius:
            template: SyliusWebBundle:Shop/Payment:show.html.twig
